version: 0.0
os: linux
files:
   - source: /
     destination: /home/ec2-user/pgscript
     
permissions:
   - object: /home/ec2-user/pgscript
     pattern: "**"
     owner: ec2-user
     mode: 777
     type:
       - file
hooks:
  AfterInstall:
    - location: ./scripts/after-install.sh
      timeout: 900
