CREATE UNIQUE INDEX IDX_ASSET_ID_PARTITION ON testschema.ASSET (ASSET_ID );
CREATE UNIQUE INDEX IDX_ASSET_TRANSACTIONID ON testschema.ASSET (TRANSACTION_ID );
CREATE INDEX IDX_ASSET_NM ON testschema.ASSET (UPPER(ISSUER_NM));
CREATE INDEX IDX_ASSET_OWNER ON testschema.ASSET (DATA_OWNER_ID);