CREATE TABLE IF NOT EXISTS testschema.asset(
    asset_id                          INTEGER NOT NULL,
    data_owner_id                     INTEGER NOT NULL,
    issuer_nm                         CHARACTER VARYING(160) NOT NULL,
    asset_state_id                    SMALLINT NOT NULL,
    name                              CHARACTER VARYING(160) NOT NULL,
    issue_dt                          INTEGER NOT NULL,
    asset_domain_cd                   CHARACTER VARYING(2),
    last_chg_user_nm                  CHARACTER VARYING(30) NOT NULL DEFAULT SESSION_USER,
    last_chg_dt_tm                    TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by_user_nm                CHARACTER VARYING(30) NOT NULL DEFAULT SESSION_USER,
    created_dt_tm                     TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    trading_region_id                 INTEGER,
    exchange_id                       INTEGER,
    issuer_id                         INTEGER,
    incorporation_country_id          SMALLINT,
    trading_currency_id               INTEGER,
    index_class_cd                    CHARACTER VARYING(1),
    preferred_identifier_type_id      INTEGER,
    major_asset_class                 CHARACTER VARYING(20),
    minor_asset_class                 CHARACTER VARYING(30),
    underlying_entity_uid             INTEGER,
    database_of_record_cd             CHARACTER VARYING(40) NOT NULL,
    maturity_dt                       INTEGER,
    single_transaction_asset_flg      BOOLEAN,
    transaction_id                    INTEGER,
    instrument_trcs_asset_class_cd    CHARACTER VARYING(40),
    last_state_chg_dt_tm              TIMESTAMP(0) WITHOUT TIME ZONE,
    portfolio_id                      INTEGER,
    quote_lot_size                    INTEGER,
    quote_currency_cd                 CHARACTER VARYING(3),
    notional_amt                      DOUBLE PRECISION,
    notional_currency_cd              CHARACTER VARYING(3),
    trade_lot_size                    INTEGER,
    settlement_convention_cd          CHARACTER VARYING(40),
    delivery_convention_cd            CHARACTER VARYING(40),
    delivery_type_cd                  CHARACTER VARYING(40),
    delivery_dt                       INTEGER,
    payoff_script                     CHARACTER VARYING(4000),
    adfin_structure_id                CHARACTER VARYING(40),
    primary_quote_uid                 INTEGER,
    seniority                         CHARACTER VARYING(40),
    doc_clause                        CHARACTER VARYING(40),
    strike_price_amt                  DOUBLE PRECISION,
    expire_dt                         INTEGER,
    option_type_cd                    CHARACTER VARYING(4),
    coupon_rate                       DOUBLE PRECISION,
    asset_type                        CHARACTER VARYING(40)
)
WITH (
OIDS=FALSE
);